export class AppApi {
    Suppliers = [{
        'SuppliersID': 1,
        'Suppliersnames': 'Apple'
    },
    {
        'SuppliersID': 2,
        'Suppliersnames': 'Samsung'
    },
    {
        'SuppliersID': 3,
        'Suppliersnames': 'OPPO'
    },
    {
        'SuppliersID': 4,
        'Suppliersnames': 'Huawei'
    },
    {
        'SuppliersID': 5,
        'Suppliersnames': 'Sony'
    }
    ];
    Categories = [{
        'CategorieID': 1,
        'CategorieName': 'Điện thoại',

    }, {
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
    },];
    //Danh sach san pham
    Products = [{
        'ProductID': 1,
        'ProductName': 'iPhone X 256GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph001.jpg',
        'Price': '32.790.000₫',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ',
        'ToDate': '',

    },
    {
        'ProductID': 2,
        'ProductName': 'iPhone X 64GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph002.jpg',
        'Price': '27.990.000₫',
        'NumView': '17',
        'NumPrice': '11',
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 3,
        'ProductName': 'iPhone 8 Plus 256GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph003.jpg',
        'Price': '26.790.000₫',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 4,
        'ProductName': 'iPhone 8 256GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph004.jpg',
        'Price': '23.790.000₫',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 5,
        'ProductName': 'iPhone 8 Plus 64GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph005.jpg',
        'Price': '21.990.000₫',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 6,
        'ProductName': 'iPhone 7 Plus 128GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph006.jpg',
        'Price': '18.990.000₫',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 7,
        'ProductName': 'iPhone 7 32GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph007.jpg',
        'Price': '22.990.000₫',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 8,
        'ProductName': 'iPhone 6 32GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph008.png',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 9,
        'ProductName': 'Samsung Galaxy S9+ 128GB',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph009.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 10,
        'ProductName': 'Samsung Galaxy Note 8',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph010.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 11,
        'ProductName': 'Samsung Galaxy S8',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph011.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 12,
        'ProductName': 'Samsung Galaxy A8',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph012.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 13,
        'ProductName': 'Samsung Galaxy C9 Pro',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph013.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 14,
        'ProductName': 'Samsung Galaxy J7+',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph014.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': '15',
        'ProductName': 'Samsung Galaxy J3 Pro',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph015.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 16,
        'ProductName': 'Samsung Galaxy J3LTE',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph016.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 17,
        'ProductName': 'OPPO F7 128GB',
        'SuppliersID': 3,
        'SuppliersName': 'OPPO',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph017.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 18,
        'ProductName': 'OPPO F5 6GB',
        'SuppliersID': 3,
        'SuppliersName': 'OPPO',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph018.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 19,
        'ProductName': 'OPPO F7',
        'SuppliersID': 3,
        'SuppliersName': 'OPPO',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph019.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 20,
        'ProductName': 'OPPO F3 Plus',
        'SuppliersID': 3,
        'SuppliersName': 'OPPO',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph020.png',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 21,
        'ProductName': 'Sony Xperia XZ24',
        'SuppliersID': 5,
        'SuppliersName': 'Sony',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph021.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 22,
        'ProductName': 'Sony Xperia XZ Premium',
        'SuppliersID': 5,
        'SuppliersName': 'Sony',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph022.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 23,
        'ProductName': 'Sony Xperia XZ Premium Pink Gold',
        'SuppliersID': 5,
        'SuppliersName': 'Sony',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph023.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 24,
        'ProductName': 'Sony Xperia XZ1',
        'SuppliersID': 5,
        'SuppliersName': 'Sony',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph024.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 25,
        'ProductName': 'Huawei Nova 3e',
        'SuppliersID': 4,
        'SuppliersName': 'Huawei',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph025.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 26,
        'ProductName': 'Huawei Nova 2i',
        'SuppliersID': 4,
        'SuppliersName': 'Huawei',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph026.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 27,
        'ProductName': 'Huawei Y7 Prime',
        'SuppliersID': 4,
        'SuppliersName': 'Huawei',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph027.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 28,
        'ProductName': 'Huawei Y7 Pro',
        'SuppliersID': 4,
        'SuppliersName': 'Huawei',
        'CategorieID': 1,
        'CategorieName': 'Điện Thoại',
        'Picture': 'Iphone/iph028.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 29,
        'ProductName': 'iPad Pro 10.5 inch Wifi 64GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph029.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 30,
        'ProductName': 'iPad Air 2 Cellular 128GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph030.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 31,
        'ProductName': 'iPad Wifi Cellular 128GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph031.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 32,
        'ProductName': 'iPad Wifi Cellular 32GB',
        'SuppliersID': 1,
        'SuppliersName': 'Apple',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph032.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 33,
        'ProductName': 'Samsung Galaxy Tab A6 10.1 Spen',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph033.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 34,
        'ProductName': 'Samsung Galaxy Tab A 8.0',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph034.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 35,
        'ProductName': 'Samsung Galaxy Tab E 9.6',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph035.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 36,
        'ProductName': 'Samsung Galaxy Tab A6 7.0',
        'SuppliersID': 2,
        'SuppliersName': 'Samsung',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph036.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 37,
        'ProductName': 'Huawei MediaPad M3 8.0',
        'SuppliersID': 4,
        'SuppliersName': 'Huawei',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph037.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 38,
        'ProductName': 'Huawei MediaPad T3 10',
        'SuppliersID': 4,
        'SuppliersName': 'Huawei',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph038.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 39,
        'ProductName': 'Huawei MediaPad T1 8.0',
        'SuppliersID': 4,
        'SuppliersName': 'Huawei',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph039.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    },
    {
        'ProductID': 40,
        'ProductName': 'Huawei MediaPad T3 7.0',
        'SuppliersID': 4,
        'SuppliersName': 'Huawei',
        'CategorieID': 2,
        'CategorieName': 'Máy tính bảng',
        'Picture': 'Ipad/iph040.jpg',
        'Price': '28.790.000',
        'NumView': 164,
        'NumPrice': 4,
        'Madein': 'Mỹ', 'ToDate': ''
    }
    ]
}
